# DouYinCommand.py Configuration File
# Required items

# Download link list
link:
  # - https://v.douyin.com/gNv_ZvhuEr0/
  - https://v.douyin.com/3uGJzMxBwTI/

# Download save path
path: ./Downloaded/

# Number of download threads
thread: 5

# Download mode (Effective when using homepage links)
mode:
  - post

# Download quantity limits
number:
  post: 3      # Number of posts (0 for all)
  like: 3      # Number of likes
  music: 3     # Number of music tracks
  mix: 3       # Number of collections
  allmix: 3    # Number of all collections

# Incremental download settings
increase:
  post: false
  like: false
  music: false
  mix: false
  allmix: false

# Download content settings
music: true       # Download background music
cover: true       # Download cover
avatar: true      # Download avatar
json: true        # Save JSON info
database: true    # Use database
folderstyle: true # Classify by folder

# Time filtering
start_time: ''
end_time: ''

# Cookie configuration (Optional)
cookie: ''

# 或使用键值对方式
cookies:
  msToken: my7nuKyrpTVEWOX-n62wR8I5EcvoMKBmvsBMnODLOtG3sn6AsR7q_jEM5jmEenyuwmHpsL25b84VhGcR4nUgv0PepA2zrSUOGHCmZVzpauYpRgbR9svMKjt2-AgNRz
  sessionid: bd1856d28d3592573fc43c7bec5194d6
  sessionid_ss: bd1856d28d3592573fc43c7bec5194d6
  sid_guard: bd1856d28d3592573fc43c7bec5194d6%7C1757747080%7C5184000%7CWed%2C+12-Nov-2025+07%3A04%3A40+GMT
  sid_tt: bd1856d28d3592573fc43c7bec5194d6
  ttwid: 1%7CmmH7jXEeDQziYDU1ZbV5bzf7luuM31p6Knl_Q6cpRJI%7C1757747088%7C8bae7013a3e95043c556c8d512917ba723c9ff0f629ddc6f9f23bb0d1bc7972c
  uid_tt: 0db1165d183a178f06d70ff7b1543a51
  uid_tt_ss: 0db1165d183a178f06d70ff7b1543a51